### ISSUE TITLE
Update lodash and csv-parse 

### ISSUE THREAD

**Issue by jsergiu** [npow/airline-codes#2]
Current versions of lodash and csv-parse that are used have some vulnerabilities according to `npm audit`. They should be updated to the latest version.

**Comment by npow** [comment]
I don't see any issues when I run `npm audit`. Can you paste the output you're getting?

```
➜  airline-codes  npm audit                                                                                                                                                         

=== npm audit security report ===

found 0 vulnerabilities
 in 12 scanned packages
```

**Comment by jsergiu** [comment]
The issue went away. Maybe the dependencies had been updated.
